### ISSUE TITLE
Needs a CI build

### ISSUE THREAD

**Issue by paulcichonski** [cisco/elsy#1]
We need a functioning CI build that will gate PRs and publish binaries for releases.

**Comment by joeygibson** [comment]
I use TravisCI for my stuff. It's easy, and is driven by a file in the repo itself.

**Comment by paulcichonski** [comment]
TravisCI sounds good to me, looks like we can install docker and compose [1] and install the lc binary so it should be fairly simple to setup.

[1] https://docs.travis-ci.com/user/docker/
