### ISSUE TITLE
sporadic memory errors during 'lc package'

### ISSUE THREAD

**Issue by paulcichonski** [cisco/elsy#4]
This happens very infrequently (maybe 1 out of 100 times), `lc package` will throw the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x514c05]

goroutine 1 [running]:
panic(0x8c0fe0, 0xc8200120d0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
stash0.eng.lancope.local/dev-infrastructure/project-lifecycle/helpers.RemoveContainersOfImage(0xc82026c848, 0x7, 0x0, 0x0)
    /go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle/helpers/docker.go:89 +0x735
stash0.eng.lancope.local/dev-infrastructure/project-lifecycle/command.RunPackage(0xc8201fe000, 0x0, 0x0)
    /go/src/stash0.eng.lancope.local/dev-infrastructure/project-lifecycle/command/package.go:62 +0x796
```

Guessing this related to 82c30e4 and/or c054cde, we should probably just revert that logic since it doesn't work in all cases (i.e., large docker compose files).

**Comment by joeygibson** [comment]
Seems strange that either of those commits could be the culprit. My inclination would be something environmental.

**Comment by paulcichonski** [comment]
You are right, it is most likely environmental..only seeing this on Jenkins instances that are running on a sorely under-provisioned VM cluster.

Will close, we can re-open if it starts showing up in other places.

**Comment by paulcichonski** [comment]
We are seeing this again, more details courtesy of @munkyboy :

This is probably a race condition.

we list containers here:
https://github.com/cisco/elsy/blob/master/helpers/docker.go#L64

iterate, then inspect each here
https://github.com/cisco/elsy/blob/master/helpers/docker.go#L72

so if a container goes away between listing it and inspecting it, boom.

This condition probably arises more often in projects with a custom  `package:` service in docker-compose. because the docker container for packaging might take a second to teardown and we immediately call this `RemoveContainersOfImage` routine
