### ISSUE TITLE
blackbox-test command calls package but does not apply image labels

### ISSUE THREAD

**Issue by paulcichonski** [cisco/elsy#56]
`RunPackage` relies on the `git-commit` arg: https://github.com/paulcichonski/elsy/blob/master/command/package.go#L95

However this is only supplied from `ci` and `package`, so when `lc blackbox-test` is run on its lonesome it delegates to `package`, but no labels get applied.

**Comment by joeygibson** [comment]
What do we use the labels for, other than non-gc? And how does this bug manifest itself? IOW, labels don't get applied, and... what then?

**Comment by paulcichonski** [comment]
context: https://github.com/cisco/elsy/pull/13

Its just provenance data (i.e., this image came from this git commit sha). It is a super edge case, but i'm hitting this because I have a rather esoteric build where I'm not calling `lc ci`, but am just calling bootstrap and blackbox-test (and relying on blackbox-test to package the image).

I've fixed this locally by just adding an `lc package` to the build and changed the blackbox-test line to be `lc blackbox-test --skip-package`.

**Comment by joeygibson** [comment]
So you want `--git-commit=xxx` added to `lc blackbox-test`? Is that right?

**Comment by paulcichonski** [comment]
Yeah, i think that should be enough.
