### ISSUE TITLE
Elsy should attach provenance metadata to docker image

### ISSUE THREAD

**Issue by paulcichonski** [cisco/elsy#6]
Sometimes it is super hard to track how an image was created (i.e., git-commit, build-number). We should be attaching this provenance metadata to the image before we publish it.

One thought would be to add this using the `--label` arg to `docker build`, during the `lc package` phase, but this will only work for Docker 1.11 and higher.

**Comment by rwhitworth** [comment]
This can be accomplished with the `LABEL` keyword in the Dockerfile.  The file could be copied, lines for labels appended, and then `-f` used to specify the Dockerfile location/name.  I know it changes the source files, but it would be a workaround.

Similarly, what versions of Docker does elsy support?  I did not see it mentioned in the `README.md`

**Comment by paulcichonski** [comment]
>I know it changes the source files, but it would be a workaround.

I think for this we can just say we only support it for docker 1.11 (and higher) and not add a workaround for lower versions.

The tasks for implementing this would be:

- update https://github.com/cisco/elsy/blob/master/command/package.go#L53 to add the right `--label` args, but only do it IFF the docker version is `>=` 1.11. 
- update the travis ci build to run with docker 1.11 so that we can test this: https://github.com/cisco/elsy/blob/master/.travis.yml#L6

>what versions of Docker does elsy support? I did not see it mentioned in the README.md

Good question :). We probably support all versions since 1.9, but we only actively test against the version the TravisCI build is coded to. Added https://github.com/cisco/elsy/issues/12 to remedy.
